server:
  port: 8080

spring: 
  application:
    name: 'facilpay-backoffice-ec'
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/facilpay-db-ec
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

logging:
  level:
    liquibase: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true

# Database migration configuration
config:
  liquibase:
    change-log: classpath:/db/facilpay-db-ec-changelog.xml
    database-change-log-table: tbl_database_migrations
    database-change-log-lock-table: tbl_database_migrations_lock

sqlDialect: org.hibernate.dialect.PostgreSQLDialect
entityPackage: br.com.facilpay.ecommerce.infra.entities
apiPackage: br.com.facilpay.ecommerce.entrypoint.rest