server:
  port: 8081

spring: 
  application:
    name: 'facilpay-payment-tx'
  cloud:
    consul:
      config:
        fail-fast: true
      host: localhost
      port: 8500
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/facilpay-db-tx
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

logging:
  level:
    liquibase: INFO

# Database migration configuration
config:
  liquibase:
    change-log: classpath:/db/facilpay-db-tx-changelog.xml
    database-change-log-table: tbl_database_migrations
    database-change-log-lock-table: tbl_database_migrations_lock

sqlDialect: org.hibernate.dialect.PostgreSQLDialect
entityPackage: br.com.facilpay.payment.infra.entities
#apiPackage: br.com.facilpay.payment.entrypoint.rest